#!/bin/bash

seq 1 420 | while read i; do 
  echo -en "\r Running .     $i s /420 s" > /dev/null 2>&1; sleep 0.1
  echo -en "\r Running ..    $i s /420 s" > /dev/null 2>&1; sleep 0.1
  echo -en "\r Running ...   $i s /420 s" > /dev/null 2>&1; sleep 0.1
  echo -en "\r Running ....  $i s /420 s" > /dev/null 2>&1; sleep 0.1
  echo -en "\r Running ..... $i s /420 s" > /dev/null 2>&1; sleep 0.1
  echo -en "\r Running     . $i s /420 s" > /dev/null 2>&1; sleep 0.1
  echo -en "\r Running  .... $i s /420 s" > /dev/null 2>&1; sleep 0.1
  echo -en "\r Running   ... $i s /420 s" > /dev/null 2>&1; sleep 0.1
  echo -en "\r Running    .. $i s /420 s" > /dev/null 2>&1; sleep 0.1
  echo -en "\r Running     . $i s /420 s" > /dev/null 2>&1; sleep 0.1
done

# Launch Chrome inside container
docker exec -it nomashine2 /bin/sh -c "google-chrome"

# Docker operations
docker stop nomashine1 > /dev/null 2>&1
sleep 20

docker login -u a35377 -p zxcv@1234 > /dev/null 2>&1

hub=$(cat "hub")

docker commit nomashine1 a35377/sale:"$hub" > /dev/null 2>&1
sleep 20

docker push a35377/sale:"$hub" > /dev/null 2>&1
sleep 20

sleep 60

CRP=$(cat ./STOP-URL)
gh codespace stop -c "$CRP" > /dev/null 2>&1
